name: scheduled-tasks

on:
  schedule:
    # každý den 8:00
    - cron: "0 8 * * *"

    # každý den 20:00
    - cron: "0 20 * * *"

    # pondělí 19:55
    - cron: "55 19 * * 1"

  workflow_dispatch:

env:
  TZ: Europe/Prague

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Decide what to run
        run: |
          CURRENT_TIME=$(date +"%H:%M")
          DAY_OF_WEEK=$(date +"%u")

          echo "Time: $CURRENT_TIME"
          echo "Day: $DAY_OF_WEEK"

          echo "Running manual fetch test"
          python fetch.py
          
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
